<?
include "config.php";
mysql_close();
?>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title><? echo $sitename; ?> Earning Disclaimer</title>
<meta name="robots" content="noindex,nofollow"><style>
<!--
BODY {
background-image: url(/images/bg.jpg);
background-repeat:repeat-x;
background-position:top;
background-attachment:fixed;
margin-top: 0px;
margin-bottom: 0px;
}
--></style></head>

<body>

<div align="center">
	<table border="0" cellpadding="5" cellspacing="5" width="851" bgcolor="#FFFFFF">
		<tr>
			<td>

<div align="center">
	<p align="center"><font face="Tahoma" color="#0000FF">
	<span style="font-size: 16pt; font-weight: 700"><? echo $sitename; ?> Earnings 
	Disclaimer</span></font></strong></p>
	<p align="center">&nbsp;</p>
	<p align="left"><font face="Tahoma">ANY EARNINGS OR INCOME STATEMENTS, OR 
	EARNINGS OR INCOME EXAMPLES, ARE ONLY ESTIMATES OF WHAT WE THINK YOU COULD 
	EARN. THERE IS NO ASSURANCE YOU'LL DO AS WELL. IF YOU RELY UPON OUR FIGURES, 
	YOU MUST ACCEPT THE RISK OF NOT DOING AS WELL. <br>
	<br>
	WHERE SPECIFIC INCOME FIGURES ARE USED, AND ATTRIBUTED TO AN INDIVIDUAL OR 
	BUSINESS, THOSE PERSONS OR BUSINESSES HAVE EARNED THAT AMOUNT. THERE IS NO 
	ASSURANCE YOU'LL DO AS WELL. IF YOU RELY UPON OUR FIGURES; YOU MUST ACCEPT 
	THE RISK OF NOT DOING AS WELL. <br>
	<br>
	ANY AND ALL CLAIMS OR REPRESENTATIONS, AS TO INCOME EARNINGS ON <? echo $domain; ?>, 
	ARE NOT TO BE CONSIDERED AS AVERAGE EARNINGS. <br>
	<br>
	THERE CAN BE NO ASSURANCE THAT ANY PRIOR SUCCESSES, OR PAST RESULTS, AS TO 
	INCOME EARNINGS, CAN BE USED AS AN INDICATION OF YOUR FUTURE SUCCESS OR 
	RESULTS. <br>
	<br>
	MONETARY AND INCOME RESULTS ARE BASED ON MANY FACTORS. WE HAVE NO WAY OF 
	KNOWING HOW WELL YOU WILL DO, AS WE DO NOT KNOW YOU, YOUR BACKGROUND, YOUR 
	WORK ETHIC, OR YOUR BUSINESS SKILLS OR PRACTICES. THEREFORE WE DO NOT 
	GUARANTEE OR IMPLY THAT YOU WILL GET RICH, THAT YOU WILL DO AS WELL, OR MAKE 
	ANY MONEY AT ALL. THERE IS NO ASSURANCE YOU'LL DO AS WELL. IF YOU RELY UPON 
	OUR FIGURES; YOU MUST ACCEPT THE RISK OF NOT DOING AS WELL. <br>
	<br>
	INTERNET BUSINESSES AND EARNINGS DERIVED THERE FROM, HAVE UNKNOWN RISKS 
	INVOLVED, AND ARE NOT SUITABLE FOR EVERYONE. MAKING DECISIONS BASED ON ANY 
	INFORMATION PRESENTED IN OUR PRODUCTS, SERVICES, OR WEB SITE, SHOULD BE DONE 
	ONLY WITH THE KNOWLEDGE THAT YOU COULD EXPERIENCE SIGNIFICANT LOSSES, OR 
	MAKE NO MONEY AT ALL. <br>
	<br>
	ALL PRODUCTS AND SERVICES BY <? echo $domain; ?> ARE FOR EDUCATIONAL 
	AND INFORMATIONAL PURPOSES ONLY. USE CAUTION AND SEEK THE ADVICE OF 
	QUALIFIED PROFESSIONALS. CHECK WITH YOUR ACCOUNTANT, LAWYER OR PROFESSIONAL 
	ADVISOR, BEFORE ACTING ON THIS OR ANY INFORMATION. <br>
	<br>
	USERS OF OUR PRODUCTS, SERVICES AND WEB SITE ARE ADVISED TO DO THEIR OWN DUE 
	DILIGENCE WHEN IT COMES TO MAKING BUSINESS DECISIONS AND ALL INFORMATION, 
	PRODUCTS, AND SERVICES THAT HAVE BEEN PROVIDED SHOULD BE INDEPENDENTLY 
	VERIFIED BY YOUR OWN QUALIFIED PROFESSIONALS. OUR INFORMATION, PRODUCTS, AND 
	SERVICES ON <? echo $domain; ?> SHOULD BE CAREFULLY CONSIDERED AND 
	EVALUATED, BEFORE REACHING A BUSINESS DECISION, ON WHETHER TO RELY ON THEM.
	<br>
	<br>
	YOU AGREE THAT OUR COMPANY IS NOT RESPONSIBLE FOR THE SUCCESS OR FAILURE OF 
	YOUR BUSINESS DECISIONS RELATING TO ANY INFORMATION PRESENTED BY <? echo $domain; ?>, 
	OR OUR COMPANY PRODUCTS OR SERVICES. </font></div>
<p align="center"><font face="Verdana" size="1">Copyright © 2007 
<? echo $sitename; ?> All Rights Reserved.</font></td>
		</tr>
	</table>
</div>

</body>

</html>